# Netlify Configuration
# This file optimizes your website for Netlify hosting

[build]
  # No build process needed for static HTML site
  publish = "."

[[headers]]
  # Security headers for better performance
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  # Handle client-side routing (if needed in future)
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # Environment variables for production
  NODE_VERSION = "18"
